config/routes.rb
Rails.application.routes.draw do

  defaults format: :json do
   get '/profile/gustavodaza', to: 'users#show', :id => '1'
  end

  root to: "users#new"
  resources :friends
  resources :users, shallow: true do
    resources :certifications
    resources :hobbies
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/certification.rb
class Certification < ApplicationRecord
  has_one_attached :document
  belongs_to :user

end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/hobby.rb
class Hobby < ApplicationRecord
  belongs_to :user

  enum category: {Música: 0, Lectoescritura: 1, Aventura: 2, Fitness: 3, Coleccionismo: 4, Entretenimiento: 5, Construcción: 6, Gastronomía: 7, }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :certifications
  has_many :friends
  has_many :hobbies
  has_one_attached :image
  accepts_nested_attributes_for :certifications, :hobbies

  before_create :image_empty

  private

  def image_empty
    unless image.attached?
      self.image.attach(io:File.open(Rails.root.join("app/assets/images/default.png")), filename: 'default.png' , content_type: "image/png")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/certifications_controller.rb
class CertificationsController < ApplicationController
  before_action :set_certification, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:index, :new, :create]


  def index
    @certifications = Certification.all
  end


  def show
  end


  def new
    @certification = Certification.create
  end


  def edit
  end


  def create
    @certification = @user.certifications.build(certification_params)
     if @certification.save
       redirect_to user_certifications_path(@user), notice: 'Certification was successfullycreated.'
     else
      render :new
    end
  end


  def update
    if @certification.update(certification_params)
      redirect_to user_certifications_path(@certification.user.id), notice: 'Certification wassuccessfully updated.'
    else
       render :edit
    end
  end

  def destroy
    @user = @certification.user.id
    @certification.destroy
    redirect_to user_certifications_path(@user), notice: 'Certification was successfully destroyed.'
  end

  private

    def set_certification
      @certification = Certification.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end


    def certification_params
      params.require(:certification).permit(:name, :url, :document)
    end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_user


  def index
    @friends = Friend.all
  end

  def search
  end

  def show
  end


  def new
    @friend = Friend.new
  end


  def edit
  end


  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_friend
      @friend = Friend.find(params[:id])
    end


    def friend_params
      params.require(:friend).permit(:alias, :url)
    end
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :set_hobby, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:index, :new, :create]


  def index
    @hobbies = Hobby.all
  end


  def show
  end


  def new
    @hobby = Hobby.new
  end


  def edit
  end


  def create
    @hobby = @user.hobbies.build(hobby_params)
      if @hobby.save
      redirect_to user_hobbies_path(@user), notice: 'Hobby was successfully created.'
      else
       render :new
    end
  end


  def update
      if @hobby.update(hobby_params)
      redirect_to user_hobbies_path(@hobby.user.id), notice: 'Hobby was successfully updated.'
      else
       render :edit
    end
  end


  def destroy
    @user = @hobby.user.id
    @hobby.destroy
     redirect_to user_hobbies_path(@user), notice: 'Hobby was successfully destroyed.'
  end

  private

    def set_hobby
      @hobby = Hobby.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    def hobby_params
      params.require(:hobby).permit(:name, :description, :preference, :category)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :age, only: [:show], unless: -> {@user.birthdate.nil?}
  before_action :set_certifications, unless: -> {@user.nil?}
  before_action :set_hobbies, unless: -> {@user.nil?}
  before_action :users_empty, only: [:show, :new], if: -> {@user.nil?}


  def index
    @users = User.all
  end


  def show
  end


  def new
    @user = User.new
  end


  def edit
  end


  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def set_hobbies
      @hobbies = @user.hobbies
    end

    def set_certifications
      @certifications = @user.certifications
    end

    def set_friends
      @friends = @user.friends
    end

    def user_params
      params.require(:user).permit(:firstname, :lastname, :subtitle, :email, :username, :bio, :birthdate, :image)
    end

    def age
      @age = Date.today.year - @user.birthdate.year
      @age -= 1 if Date.today < @user.birthdate + @age.years
    end

    def users_empty
      @users = User.all
      redirect_to action: 'show', id: 1 if !@users.blank?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/certifications_helper.rb
module CertificationsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/certifications/edit.html.haml
%h1 Edit Certification

= form_with(model: [@certification], local: true) do |f|
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :file
    = f.file_field :document, :required => true

  .actions
    = f.submit

app/views/certifications/index.html.haml
%p#notice= notice
%h1 Certifications
%table.table
  %thead
    %tr
      %th Name
      %th File
  %tbody
    - @certifications.each do |certification|
      %tr
        %td= certification.name
        %td= link_to 'View Certification', certification.document
        %td= link_to 'Edit', edit_certification_path( certification )
        %td= link_to 'Destroy', certification, method: :delete, data: { confirm: 'Are you sure?' }
%br/

.container
  .row
    .col-1
      =button_to 'New', new_user_certification_path(@user), method: :get
    .col-1
      =button_to 'Back to Edit', edit_user_path(@user), method: :get

app/views/certifications/new.html.haml
%h1 New Certification

= form_with(model: [@user, @certification], local: true) do |f|
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :file
    = f.file_field :document, :required => true

  .actions
    = f.submit

app/views/friends/new.html.haml
%h1 New friend

= render 'form'

= link_to 'Back', friends_path

app/views/friends/show.html.haml
.container.border.rounded
  .row
    .col-lg
      %h1.text-center
        = @user.firstname
        = @user.lastname
  .row
    .col
      %h4.text-center
        =@user.subtitle
.container.border.rounded
  .row
    .col-lg
      %h3 &nbsp Basic Information
  .row
    .col-lg-7
      %p
      = @user.bio
      %p
      %p
        %b Edad: &nbsp
        = @age
      %p
      %p
        %b Correo Electrónico: &nbsp
        = link_to @user.email
    .col-lg-2
    .col-lg-2
      = image_tag @user.image, class:"img"

.container
  .row
    %h3 &nbsp Hobbies
  .row
    - @hobbies.each do |h|
      .col-md-4.col-sm-6
        .card
          .card-body
            %h4.card-title
              = h.name
            %h6
              = h.category
            %p
              = h.description
            %p
              = h.preference

.container
  .row
    %h3 &nbsp Certifications
  .row
    .col
      %ul
        - @certifications.each do |certification|
          %li.list-group-item
            = certification.name
            = link_to 'View file', certification.document
.container.border.rounded
  .row
    .col-lg-11
    .col-lg-1
      =button_to 'Edit', edit_user_path(@user), method: :get

app/views/hobbies/edit.html.haml
%h1 Edit Hobby

= form_with(model: [@hobby], local: true) do |f|
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :preference
    = f.number_field(:preference, :min => 1, :max =>5)
  .field
    = f.label :category
    = f.select :category, Hobby.categories.keys.map {|cat| [cat.titleize, cat]}

  .actions
    = f.submit

app/views/hobbies/index.html.haml
%p#notice= notice
%h1 Hobbies
%table.table
  %thead
    %tr
      %th Name
      %th Description
      %th Preference
      %th Category
  %tbody
    - @hobbies.each do |hobby|
      %tr
        %td= hobby.name
        %td= hobby.description
        %td= hobby.preference
        %td= hobby.category
        %td= link_to 'Edit', edit_hobby_path( hobby )
        %td= link_to 'Destroy', hobby, method: :delete, data: { confirm: 'Are you sure?' }
%br/

.container
  .row
    .col-1
      =button_to 'New', new_user_hobby_path(@user), method: :get
    .col-1
      =button_to 'Back to Edit', edit_user_path(@user), method: :get

app/views/hobbies/new.html.haml
%h1 New Hobby

= form_with(model: [@user, @hobby], local: true) do |f|
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :preference
    = f.number_field(:preference, :min => 1, :max =>5)
  .field
    = f.label :category
    = f.select :category, Hobby.categories.keys.map {|cat| [cat.titleize, cat]}
  .actions
    = f.submit 'Save'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HackProfile
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/users/edit.html.haml
%h1 Editing User

= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :firstname, "Name"
    = f.text_field :firstname, :required => true
  .field
    = f.label :lastname, "Last Name"
    = f.text_field :lastname, :required => true
  .field
    = f.label :email
    = f.email_field :email, :required => true
  .field
    = f.label :username
    = f.text_field :username, :required => true
  .field
    = f.label :subtitle
    = f.text_field :subtitle
  .field
    = f.label :biography
    = f.text_area :bio
  .field
    = f.label :birthdate
    = f.date_select(:birthdate , :start_year => 1940, :end_year => Date.current.year - 10)
  .field
    =f.label :Photo
    =image_tag @user.image, class:"img"
  .field
    =f.file_field :image
  .actions
    = f.submit 'Save'
.container
  .row
    .col-2
      =button_to 'Add Hobbies', user_hobbies_path(@user), method: :get
    .col-2
      =button_to 'Add Certificates', user_certifications_path(@user), method: :get
    .col-2
      =button_to 'Add Friends', search_path, method: :get
    .col-2
      =button_to 'Back to Profile', user_path(@user), method: :get

app/views/users/index.html.haml
%h1 Listing Users

%table
  %thead
    %tr
      %th Name
      %th Last Name
      %th Subtitle
      %th Email
      %th Username
      %th Biography
      %th Age
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.firstname
        %td= user.lastname
        %td= user.subtitle
        %td= user.email
        %td= user.username
        %td= user.bio
        %td= user.birthdate
        %td= link_to 'View Profile Picture', user.image
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New User

= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :firstname, "Name"
    = f.text_field :firstname, :required => true
  .field
    = f.label :lastname, "Last Name"
    = f.text_field :lastname, :required => true
  .field
    = f.label :email
    = f.email_field :email, :required => true
  .field
    = f.label :username
    = f.text_field :username, :required => true

  .actions
    = f.submit 'Save'

= link_to 'Back', users_path

app/views/users/show.html.haml
.container.border.rounded
  .row
    .col-lg
      %h1.text-center
        = @user.firstname
        = @user.lastname
  .row
    .col
      %h4.text-center
        =@user.subtitle
.container.border.rounded
  .row
    .col-lg
      %h3 &nbsp Basic Information
  .row
    .col-lg-7
      %p
      = @user.bio
      %p
      %p
        %b Edad: &nbsp
        = @age
      %p
      %p
        %b Correo Electrónico: &nbsp
        = link_to @user.email
    .col-lg-2
    .col-lg-2
      = image_tag @user.image, class:"img"

.container
  .row
    %h3 &nbsp Hobbies
  .row
    - @hobbies.each do |h|
      .col-md-4.col-sm-6
        .card
          .card-body
            %h4.card-title
              = h.name
            %h6
              = h.category
            %p
              = h.description
            %p
              = h.preference

.container
  .row
    %h3 &nbsp Certifications
  .row
    .col
      %ul
        - @certifications.each do |certification|
          %li.list-group-item
            = certification.name
            = link_to 'View file', certification.document
.container.border.rounded
  .row
    .col-lg-11
      %p
        %b Developed By: &nbsp
        Gustavo Daza. 2018
    .col-lg-1
      =button_to 'Edit', edit_user_path(@user), method: :get